- app/models/user.rb
Completed the user model. Please check!
> completed the user model

- app/models/appointment.rb
- app/models/user.rb
I completed the appointment model. Please check!
> Complete appointment model

- Gemfile
- Gemfile.lock
- db/migrate/20190527085101_change_oppening_hour_name.rb
- db/schema.rb
- db/seeds.rb
created seeds for users, doctros and appointments,
added new gemfile (faker)
renamed column in doctors from oppening_hour to opening_hour with new migration
> created seeds and changed column name

- app/controllers/doctors_controller.rb
- app/views/doctors/index.html.erb
- app/views/doctors/show.html.erb
- config/routes.rb
- test/controllers/doctors_controller_test.rb
created doctors controller. I will add parameters for doctor search tomorrow.
> created doctors controller

- .gitignore
- Gemfile
- Gemfile.lock
set up connection to cloudinary
next step: carrierwave to upload pictures to models
> set up cloudinary

- app/assets/stylesheets/components/_footer.scss
- app/views/shared/_footer.html.erb
This is the simplest form of a footer so we can add any information that fits later
> fixed the footer with only the text and removed the social media links

- app/policies/user_policy.rb
- test/policies/user_policy_test.rb
Added user policy. Will work on the actual policy setting later.
> added user policy

- Gemfile
- Gemfile.lock
- app/models/doctor.rb
- app/uploaders/photo_uploader.rb
- db/migrate/20190528021359_add_photo_to_doctors.rb
carrierwave gem
photo column to doctors (migration)
photo uploader to doctorscontroller
> set up carrierwave and added photo column to doctors

- db/schema.rb
- db/seeds.rb
random photos through my cloudinary
> added photos to seeds

- app/controllers/pages_controller.rb
I changed pages controller so that pages#home will be displayed without login.
> updated pages_controller

- app/policies/doctor_policy.rb
params went to doctor_policy for now, when we add the create method for doctors we can require these 
(https://github.com/varvet/pundit#strong-parameters)
> added params to doctors

- app/controllers/application_controller.rb
- app/views/devise/registrations/new.html.erb
- app/views/shared/_navbar.html.erb
Added last_name, first_name fields on user signup form, added params on application controller, added link from navbar to signup page.
> signup-flow

- app/controllers/doctors_controller.rb
Updated doctors controller so that doctors#index can be viewed from everyone
> allowed doctors#index to be viewed from everyone

- .gitignore
- app/assets/stylesheets/components/_carddoctors.scss
- app/assets/stylesheets/components/_index.scss
- app/views/doctors/index.html.erb
> doctor_view

- app/views/doctors/confirmations/new.html.erb
- app/views/doctors/mailer/confirmation_instructions.html.erb
- app/views/doctors/mailer/email_changed.html.erb
- app/views/doctors/mailer/password_change.html.erb
- app/views/doctors/mailer/reset_password_instructions.html.erb
- app/views/doctors/mailer/unlock_instructions.html.erb
- app/views/doctors/passwords/edit.html.erb
- app/views/doctors/passwords/new.html.erb
- app/views/doctors/registrations/edit.html.erb
- app/views/doctors/registrations/new.html.erb
- app/views/doctors/sessions/new.html.erb
- app/views/doctors/shared/_error_messages.html.erb
- app/views/doctors/shared/_links.html.erb
- app/views/doctors/unlocks/new.html.erb
- app/views/users/confirmations/new.html.erb
- app/views/users/mailer/confirmation_instructions.html.erb
- app/views/users/mailer/email_changed.html.erb
- app/views/users/mailer/password_change.html.erb
- app/views/users/mailer/reset_password_instructions.html.erb
- app/views/users/mailer/unlock_instructions.html.erb
- app/views/users/passwords/edit.html.erb
- app/views/users/passwords/new.html.erb
- app/views/users/registrations/edit.html.erb
- app/views/users/registrations/new.html.erb
- app/views/users/sessions/new.html.erb
- app/views/users/shared/_error_messages.html.erb
- app/views/users/shared/_links.html.erb
- app/views/users/unlocks/new.html.erb
- config/initializers/devise.rb
rails generate devise:views users
rails generate devise:views doctors
> added specific devise views for users and doctorsL

- app/assets/stylesheets/components/_footer.scss
- app/views/layouts/application.html.erb
- app/views/shared/_footer.html.erb
- app/views/shared/_navbar.html.erb
Please re-make the footer with the flex-box.. thankyou
> Reinvent footer 3

- app/controllers/doctors_controller.rb
- app/policies/doctor_policy.rb
- app/views/doctors/show.html.erb
> just_show_doctors

- app/views/pages/home.html.erb
search bar searches all doctors (no filtering by city or specialty yet)
> Search bar

- app/assets/stylesheets/components/_footer.scss
- app/views/layouts/application.html.erb
put all main components (navbar, yield, footer) in flexbox
> footer always at bottom, even when scrolling

- app/views/doctors/index.html.erb
> fix_index_link_to_show

- app/controllers/appointments_controller.rb
- app/policies/appointment_policy.rb
- app/views/appointments/index.html.erb
User can now list all the appointment they have.. DISCLAIMER "No styling is done, just the skeleton of the list" Thank You
> user can see all the appointments he/she has

- app/controllers/doctors/appointments_controller.rb
- app/views/doctors/appointments/index.html.erb
- app/views/shared/_navbar.html.erb
- config/routes.rb
- test/controllers/doctors/appointments_controller_test.rb
This is work in progress. Will complete this one after Thursday.
> created doctors/appointments controller

- app/controllers/application_controller.rb
- app/models/doctor.rb
- app/views/appointments/index.html.erb
Created a method to concatenate the first name and last name. Please push it to master :100:  :)
> Add method fullname

- app/views/users/registrations/new.html.erb
- app/views/users/sessions/new.html.erb
- app/views/users/shared/_links.html.erb
aligned them center and added some buttons style using bootstrap
> added css (a little bit) to the forms in the app

- app/assets/stylesheets/components/_body.scss
- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/components/_index.scss
Updated the body background color to white to match with the Figma file
> changed background color to white

- app/controllers/appointments_controller.rb
- app/policies/appointment_policy.rb
- app/policies/doctor_policy.rb
- app/views/appointments/new.html.erb
- db/seeds.rb
> Simple form appointment

- app/views/shared/_navbar.html.erb
There was a bug before . now it is fixed .. nothing big. Please review and merge . Thank you :)
> removed the unnecessary code and refractor the code to its simplest

- app/views/doctors/show.html.erb
Added the new styling for the show page and some features (buttons). Please Review and merge. :+1:  :)
> Added the home button to the show page and fixed the booking button

- app/views/doctors/show.html.erb
display available times
need to style and connect to form
> displaying available times

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/components/_date.scss
- app/controllers/doctors_controller.rb
- app/models/doctor.rb
> map_dont_finish

- app/views/appointments/new.html.erb
Added some typo and added some margins and centered it
> added new style to app orm

- db/seeds.rb
100 apointments
login for appointment every 30 minutes
> made better appointment seeds

- app/controllers/appointments_controller.rb
- app/views/appointments/new.html.erb
- app/views/doctors/show.html.erb
> connect create appointment with appointment time

- app/views/appointments/new.html.erb
> fix_new_appointment

- app/views/users/sessions/new.html.erb
- app/views/users/shared/_links.html.erb
> fixed the form alignment

- app/views/doctors/sessions/new.html.erb
- app/views/users/sessions/new.html.erb
- app/views/users/shared/_links.html.erb
The job is done and both the form are the same. Please merge and Thankyou. :+1: :)
> make both the form identical

- app/views/doctors/show.html.erb
Created the "Back to list" button
> added the new button

- app/assets/stylesheets/components/_card-home.scss
- app/views/shared/_navbar.html.erb
Added the link on the oppointments
> added the working link for both user and Doctor

- app/views/shared/_navbar.html.erb
Added the search bar on as expected on the navbar . Please Review and Merge. (P.s. You are doing a great job keep it up)
> added the new search bar on the navbar except on the home page

- app/views/doctors/show.html.erb
show unavailabel appointments as busy
> Filter appointments

- app/views/pages/home.html.erb
Done with the cards no more editing ... lol. Please review and merge . Thank you
> added the margina and style for the cards

- app/views/doctors/show.html.erb
fixed the size of all image to a standard image thumbnail size. Please review and Merge. Thnakyou Rei :+1:
> Fix the pic

- app/models/doctor.rb
- app/views/shared/_navbar.html.erb
Guess What? the Navbar comes with a brand new Search Category. Please Merge. Thankyou.. :)
> fixed the search bar

- app/views/shared/_navbar.html.erb
Please merge nothing to review .. Thank you
> Added placeholders in the form

- app/controllers/appointments_controller.rb
- app/views/doctors/show.html.erb
appointments created automatically
> Autoappointment

- app/views/doctors/show.html.erb
Created a Kawai button :pager: :P
> added new button

- app/assets/stylesheets/components/_card-detail.scss
- app/views/doctors/show.html.erb
> fixed the show

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_simple-calendar.scss
- app/views/doctors/appointments/index.html.erb
- app/views/layouts/application.html.erb
Created the reject button and added some styling
> Refined the map kinda looks better tbh

- Gemfile
- Gemfile.lock
> it is fixed

- app/assets/stylesheets/components/_card-detail.scss
- app/assets/stylesheets/components/_card-product.scss
- app/assets/stylesheets/components/_simple-calendar.scss
- app/views/doctors/index.html.erb
- app/views/shared/_calendar.html.erb
changed the style of the index page.. looks more cleaner. Thankyou and please merge. :+1:
> added some styling to the calender

- app/assets/stylesheets/components/_simple-calendar.scss
- app/views/layouts/application.html.erb
changed the color to grey scale on the calender . please review and merge
> added new colors to the calender

- app/views/doctors/sessions/new.html.erb
- app/views/users/sessions/new.html.erb
Changed the alignment of the login pages by adding some inner margin and outer padding. :) :+1: Please Review and Merge . Thankyou Rei
> alignment of the forms both patient and doctors

- app/views/shared/_calendar.html.erb
> added grey scale style to the calender in the index page of users

- app/assets/stylesheets/components/_simple-calendar.scss
- app/views/shared/_calendar.html.erb
Please merge Thank you.. Just changed the color of the calender
> added the color to table and removed the busy sign
